;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 general.INC                                ;
;                                General Constants                           ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains general constants.
;
; Revision History:
;	 11/5/15  David Qu			initial revision

; General constants
TRUE                EQU     1       ; Boolean true value.
FALSE               EQU     0       ; Boolean false value.

; Processor size dependent values
MAX_SIGNED_VALUE    EQU     32767   ; Maximum signed 16-bit value.
MIN_SIGNED_VALUE    EQU     32768   ; Minimum signed 16-bit value.