;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 general.INC                                ;
;                                General Constants                           ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains general constants.
;
; Revision History:
;	 11/5/15  David Qu			initial revision

; General constants
TRUE                EQU     1       ; Boolean true value.
FALSE               EQU     0       ; Boolean false value.

ASCII_NULL          EQU     0       ; ASCII decimal value for NULL character.
ASCII_RETURN        EQU     13      ; ASCII decimal value for carriage return.
