;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  motorMn.inc                               ;
;                             RoboTrike Motor Main Loop                     ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the RoboTrike Motor Main Loop, which
; processes the motor system events, which come from the motors, parser, and
; serial.
;
; Revision History:
;	 12/3/15  David Qu			initial revision
