;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  string.inc                                ;
;                             RoboTrike String Constants                     ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the RoboTrike string display constants.
;
; Revision History:
;	 12/3/15  David Qu			initial revision

BUFFER_SIZE     EQU     16      ; Size of string buffer for RoboTrike
                                ; display messages.