;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 hw7main.INC                                ;
;                             Main file Constants                            ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains constants for the hw7main test program.
;
; Revision History:
;    11/21/15 David Qu          initial revision

; Event constants
TEST_BAUD_RATE      EQU     19200     ; Value to test setSerialBaudRate.
TOGGLE_PARITY_NUM   EQU     6         ; Times to toggle parity.