;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 events.INC                                 ;
;                             Event Type Constants                           ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains Event Type constants for encoding and parsing events.
;
; Revision History:
;	 11/5/15  David Qu			initial revision

; Event constants
KEYPRESS_EVENT      EQU     1       ; Value for a keypress event. (Actual value
                                    ; will be determined once all events are 
                                    ; determined).